### ISSUE TITLE
List footguns in the documentation

### ISSUE THREAD

**Issue by abocquet** [dynamiqs/dynamiqs#241]
Due to Pytorch backend, there are a number of mistakes that one will probably make when switching from Qutip to Dynamiqs. Let's list them here and write a warning in the documentation at some point (like [Jax does](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html) for instance)

I'll start : 
- use of `@` instead of `*` for matrix multiplication
- need to write `M - alpha * I` instead of `M - alpha` where `M` is a matrix, `I` the identity and `alpha` a scalar
- forgetting to put tensors on the GPU (not a footgun but very annoying)

**Comment by pierreguilmin** [comment]
Niceee! Let me add:
- use single precision on GPUs, except if double precision is supported with good performances (which is rare)
- use `@` or `torch.linalg.matrix_power` instead of `**` for matrix power (`a @ a` is different from `a**2`)
- use `.mH` and not `.dag()` for adjoint
- (very niche) A100 > use `torch.set_float32_matmul_precision('high')` to use the new NVIDIA `TensorFloat32` type for a huge speedup
- use batching instead of for loops
