### ISSUE TITLE
Cancelling the restriction that tsave in dq.sesolve must be monotonically increasing

### ISSUE THREAD

**Issue by littlebaker** [dynamiqs/dynamiqs#536]
Hello everyone.
Since the evolution dominated by Schrödinger equation is unitary, solving for time-reverse evolution is possible. Therefore, using tsave as (t0, t1) and t1 < t0  (with dt0 < 0) should be allowed. 
the function `dq.sesolve` currently use `check_times` which will ensure that 

> Argument {argname} must be sorted in strictly ascending order.'

Maybe it's possible to cancel the restriction.

**Comment by gautierronan** [comment]
If you are using `dq.sesolve`, and want to simulate in reverse time, you could just use `H = -H`. This will give the same evolution as if you were inverting time, since the propagator reads $U(t)=\exp(-i t H)$ so $U(-t) = \exp(i t H) = \exp(-i t (-H))$.

For `dq.mesolve` this would not be true however. If this is a use-case for you we can discuss implementing it. We never tried but I'm not sure that solvers are compatible with descending order `tsave`. But that could require only minor changes.

**Comment by littlebaker** [comment]
Yeah, that's true. Maybe this is not nescessory. 
In Liouvillian space this is not true indeed. for `dq.mesolve`
